version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: degraoEmgrao_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_senha_forte
      MYSQL_DATABASE: degraoEmgraoDb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
